### ISSUE TITLE
完善语音查询文字匹配

### ISSUE THREAD

**Issue by zp-xu** [XJ-GTD/GTD2#108]

**Comment by leonxi** [comment]
需求理解
1、例如日程记录的时候会使用开会，晨会，需求会，项目进度确认等词汇，查询的时候，会使用有哪些会议，目前这种情况无法提供准确的结果

**Comment by leonxi** [comment]
实现方案
1、服务端增加对每个记录的日程进行nlp理解，识别出每个日程相关联的标签(会议，考试，行程，托福等等)
2、增加消息协议，把第一步识别出来的标签通过消息发送到手机客户端
3、手机端增加保存该标签的字段，并根据收到的消息，把标签保存到对应的日程中
4、当用户通过语音查询的时候，服务器端在目前的消息协议基础上，会根据nlp增加返回本次查询可能的标签
5、客户端增加通过标签查询的功能

**Comment by leonxi** [comment]
准备使用RASA NLU(自然语言理解)完成
一句话或者日程标题的分类
例如:
通知许兆平明天上午来公司开会   ->  会议
公司开会 -> 会议
告诉张金洋明天晚上一起吃饭 -> 饭局, 约会

**Comment by leonxi** [comment]
为什么使用RASA NLU
因为讯飞AIUI有调用次数限制, 收费版也会因为调用次数高而增加费用
另外，我们未来需要建立自己的NLU服务，开源的RASA NLU是一个目前时点最好的选择

**Comment by leonxi** [comment]
![image](https://user-images.githubusercontent.com/9960754/58459025-11acf500-815d-11e9-8cd8-9e5d130221e1.png)
增加客户端数据表用于日程标注

**Comment by leonxi** [comment]
目前使用nlp分词算法（ansj_seg），对目标词进行标记，通过标记进行分类实现

**Comment by leonxi** [comment]
v2.4版本开发完成
语义标签目前只支持会议类型，其它类型逐步完善
