### ISSUE TITLE
推送、显示单日日程

### ISSUE THREAD

**Issue by zp-xu** [XJ-GTD/GTD2#109]

**Comment by leonxi** [comment]
实现服务端消息推送，支持iOS和Android

**Comment by leonxi** [comment]
每天上午推送当日日程提醒
1、菜单的可选项（目前的设置）画面增加当日日程提醒设置
可以打开或者关闭当日日程提醒，并设置提醒时间，默认为当地上午8：30
提醒设置后，在指定的设置时间推送提醒消息
点击消息后，打开当日日程画面，浏览当天的日程安排

**Comment by leonxi** [comment]
增加语音播报功能

**Comment by leonxi** [comment]
每日简报功能已完成
语音播报每日简报功能后续追加

**Comment by leonxi** [comment]
语音播报功能已增加
