### ISSUE TITLE
日历，渲染很慢会导致刚进入app的时候日历部分日期无法显示，需要过一段时间才能显示

### ISSUE THREAD

**Issue by mm1079** [XJ-GTD/GTD2#12]
日历，渲染很慢，会导致刚进入app的时候日历部分日期无法显示，需要过一段时间才能显示
![img_0382](https://user-images.githubusercontent.com/32596785/51458703-21709300-1d91-11e9-9984-975278d2ca71.png)

**Comment by wuyu616818** [comment]
渲染设置延迟2s显示，非bug
