### ISSUE TITLE
语音界面，文字输入复杂的话发送完无反应

### ISSUE THREAD

**Issue by 17638848830** [XJ-GTD/GTD2#18]
语音界面用文字输入时，输入 我今天有什么任务，无任何回复，发送出去的话也没显示在页面
![default](https://user-images.githubusercontent.com/42716110/51459248-d9eb0680-1d92-11e9-9b60-41b9ad652184.jpg)
![2](https://user-images.githubusercontent.com/42716110/51459249-dd7e8d80-1d92-11e9-9edb-e1fa0a061f7b.jpg)

**Comment by leonxi** [comment]
@wuyu616818 优先解决

**Comment by wuyu616818** [comment]
已解决
