### ISSUE TITLE
查看日程界面无返回

### ISSUE THREAD

**Issue by 17638848830** [XJ-GTD/GTD2#21]
查看日程界面无返回按钮，点击白色边框外围返回很难点到，用户体验差、
查看日程 进入编辑界面删除此日程，后返回的界面是日程详情页面，感觉像是没删掉。
日程详情什么也不填可以直接保存。保存完后页面无跳转无任何
![default](https://user-images.githubusercontent.com/42716110/51460082-77dfd080-1d95-11e9-8656-9a49d714b5b5.jpg)
![2](https://user-images.githubusercontent.com/42716110/51460124-8ded9100-1d95-11e9-81f5-bbd175753e2f.jpg)

**Comment by 17638848830** [comment]
![default](https://user-images.githubusercontent.com/42716110/51460376-369bf080-1d96-11e9-9f71-cea87bb38319.jpg)

**Comment by leonxi** [comment]
@wuyu616818 优先解决

**Comment by kangtotest** [comment]
@17638848830 日程删除后未刷新页面，但日程已修改，页面刷新暂时手动刷新

**Comment by wuyu616818** [comment]
已解决
