### ISSUE TITLE
日历上有日程查不到

### ISSUE THREAD

**Issue by 17638848830** [XJ-GTD/GTD2#25]
日历上1月26号我有日程安排，但是查询时查不到日程
![null](https://user-images.githubusercontent.com/42716110/51461599-7ca68380-1d99-11e9-9a06-b74627d9cdac.jpg)
![null](https://user-images.githubusercontent.com/42716110/51461607-8203ce00-1d99-11e9-93d1-bc0c52f300e7.jpg)

**Comment by leonxi** [comment]
@wuyu616818 优先解决

**Comment by wuyu616818** [comment]
已解决查询不到的问题
