### ISSUE TITLE
目前测试需要的语料

### ISSUE THREAD

**Issue by 17638848830** [XJ-GTD/GTD2#32]
1、发消息给Tony，你上次发我的行程单弄丢了，麻烦你重新发我一份，谢谢！
2、麻烦装一下这个app，通过这个app发给我 
3、帮我打开Tony发给我的行程单。
4、帮我查下昨天交代给曹萍、黄伟超、小飞飞的工作做完了吗？
5、帮我发消息给曹萍、黄伟超、小飞飞，叫他们安装一下这个app，把昨天交代他们的工作任务发我一下，谢谢！
6、还有多久发工资？
7、更改工资发放日期为每月15号。
8、你们春节有空吗，找个时间出来吃饭
9、好啊，我这几天有空
10、那我们在11号聚会吧，我订好地点后发给大家
11、晚上7点，将该行程推送给吴琪，肖佳杰，赵阳，留言，这个地方，如何
12、莉莉，咱们顶峰那个项目合同结算日期是什么时候来着，尾款啥时候能收到。要不这样吧，你把合同从日历App推给我，我方便查看。

**Comment by wuyu616818** [comment]
1.3.4.5.6。11.12添加。2缺少主语。7-10对话内容暂不实现
