### ISSUE TITLE
冥王星与本地日历日程同步信息不一致，全天日程出现两天日程

### ISSUE THREAD

**Issue by forget1228** [XJ-GTD/GTD2#35]
![_20190122101801](https://user-images.githubusercontent.com/42605743/51508308-9abec300-1e2f-11e9-84cc-e3411effa79d.jpg)
![_20190122101802](https://user-images.githubusercontent.com/42605743/51508310-9b575980-1e2f-11e9-98d0-e0b5791aa690.jpg)
![_20190122101803](https://user-images.githubusercontent.com/42605743/51508311-9beff000-1e2f-11e9-861b-7d3d98a3f1a1.jpg)
![_20190122101804](https://user-images.githubusercontent.com/42605743/51508314-9c888680-1e2f-11e9-8bf2-6d5f3d2356a4.jpg)

**Comment by wuyu616818** [comment]
已解决
