### ISSUE TITLE
后台挂机影响其他程序功能

### ISSUE THREAD

**Issue by 17638848830** [XJ-GTD/GTD2#41]
冥王星在后台挂机时其他程序无法使用语音功能
![default](https://user-images.githubusercontent.com/42716110/51523070-ce1c4480-1e65-11e9-8686-1446c5922386.jpg)附上打开百度地图时
![default](https://user-images.githubusercontent.com/42716110/51523096-df655100-1e65-11e9-83aa-49096b87ae03.jpg)
附上打开浏览器时

**Comment by wuyu616818** [comment]
已解决
