### ISSUE TITLE
短信登录，页面显示成功，未收到短信

### ISSUE THREAD

**Issue by leonxi** [XJ-GTD/GTD2#42]
如题
![_20190123135503](https://user-images.githubusercontent.com/9960754/51586023-8ef9fc00-1f16-11e9-817b-5975b4f87ac2.png)

为了测试方便，短信验证码在后台日志中打出来
![image](https://user-images.githubusercontent.com/9960754/51586071-b81a8c80-1f16-11e9-9736-8e21ca76d064.png)

**Comment by wuyu616818** [comment]
已解决
