### ISSUE TITLE
添加日程中 同一个联系人会以电话号码和名称分别显示

### ISSUE THREAD

**Issue by mm1079** [XJ-GTD/GTD2#43]
![image](https://user-images.githubusercontent.com/32596785/51666606-3e0f0400-1ff9-11e9-984a-e5ceb10b259e.png)
![image](https://user-images.githubusercontent.com/32596785/51666689-6e56a280-1ff9-11e9-92c7-30d2e1e72ddb.png)

**Comment by wuyu616818** [comment]
已解决
