### ISSUE TITLE
添加联系人及发送日程问题

### ISSUE THREAD

**Issue by huangjie1118** [XJ-GTD/GTD2#44]
![image](https://user-images.githubusercontent.com/46882920/51819077-1e831e80-230c-11e9-8c38-034c7f5b961c.png)

操作步骤：
1.登录黄杰账号，添加联系人 备注曹萍16670129762，曹萍此时未注册，添加成功（此时未选择接受该用户的推送）
2.长按1月31日，创建日程赶火车，选择参与人曹萍和自己，提示创建失败，回到日历主页却显示了刚刚创建的日程，点击查看，该日程中参与者显示为空。
2.1 长按2月1日，创建日程赶高铁，选择参与人曹萍，提示创建成功，日历中2月1号显示赶高铁日程。
3.拿曹萍手机注册并登录16670129762用户后，查看无1月31日及2月1号日程。
4.在曹萍账号添加联系人黄杰18901690421，选择接受该用户的推送，发现黄杰账户参与者中出现如图所示情况，系统给我自动生成了个参与者，号码为曹萍的号码16670129762。
5.新建日程，同时选择曹萍及系统创建的“曹萍”，发送后，曹萍用户都接收不到日程信息。
问题结论：
1.添加联系人，出现重复账户
2.发送日程，不能包括自己账户，包括会报错
3.发送日程，只能本机查看，参与者查看不到日程

**Comment by wuyu616818** [comment]
1.是测试数据错误
2.3.已解决
