### ISSUE TITLE
特点情况下，日程发送bug

### ISSUE THREAD

**Issue by huangjie1118** [XJ-GTD/GTD2#45]
再现情况：
我的账户在1月30日无日程，席总的账户在1月30日有一个日程
1.我发送一个1月30日的日程给席总，席总能接收到
2.用席总的账户在1月30日再发送一个日程给我，我这边接收不到

**Comment by huangjie1118** [comment]
@wuyu616818

**Comment by wuyu616818** [comment]
@huangjie1118 不能再现
