### ISSUE TITLE
创建群组后群组画面没有显示

### ISSUE THREAD

**Issue by leonxi** [XJ-GTD/GTD2#51]
再现步骤
1、通过菜单打开群组画面
2、点击右上角创建
3、输入“冥王星”，点击保存
4、画面自动迁移到群组画面

最新创建的群组没有显示在群组画面，返回菜单并重新进入群组画面后，创建的群组才显示出来

**Comment by leonxi** [comment]
补充
创建群组后，应该进入添加联系人的画面，不应该返回群组画面

**Comment by dinggao** [comment]
返回群组界面
