### ISSUE TITLE
群组添加联系人可以重复添加

### ISSUE THREAD

**Issue by leonxi** [XJ-GTD/GTD2#52]
再现步骤
1、群组画面点击群组"冥王星"，进入群组添加联系人画面
2、点击添加联系人，进入选择联系人画面
3、输入135，然后删除531，画面显示一系列联系人
4、然后选择其中所有人，点击右上角添加
5、返回群组画面，显示所添加的联系人
6、再次点击右上角添加
7、重复3 ~ 4步骤
8、返回群组画面，显示两次添加的人员

两次添加的人员有重复添加的人员，都显示在群组人员列表中，
a、应该去除重复的人员
b、选择人员的时候应该去除已添加的人员/显示已添加
c、重复人员应该不添加到群组中
d、既然删除条件之后显示所有联系人，在添加联系人页面初始化的时候，没有输入条件的时候也应该显示所有联系人

![image](https://user-images.githubusercontent.com/9960754/55472470-c257b600-563e-11e9-94d6-192948baf72a.png)

**Comment by dinggao** [comment]
重复添加已解决
