### ISSUE TITLE
群组多次添加联系人之后，返回按钮没有直接返回菜单画面

### ISSUE THREAD

**Issue by leonxi** [XJ-GTD/GTD2#53]
再现步骤
1、菜单页面点击群组，进入群组画面
2、点击某个群组"冥王星"，进入"冥王星"群组画面
3、点击右上角添加，进入选择联系人画面
4、选择联系人后点击确定，返回"冥王星"群组画面
5、重复步骤3~4
6、重复步骤3~4
7、点击左上角返回按钮

没有直接返回菜单画面

**Comment by dinggao** [comment]
已解决
