### ISSUE TITLE
日程列表页面选择日期的日程显示位置在顶部

### ISSUE THREAD

**Issue by leonxi** [XJ-GTD/GTD2#54]
再现步骤
1、打开冥王星App，进入日历画面
2、双击4月4日，进入日程页面

默认显示4月4日的日程，但是被显示在了顶部，内容并被头部菜单遮住了

![image](https://user-images.githubusercontent.com/9960754/55473108-61c97880-5640-11e9-8e8e-b13266eb3b8f.png)

应该显示在页面中间
![image](https://user-images.githubusercontent.com/9960754/55473155-802f7400-5640-11e9-8edb-3ed4159ed00c.png)

**Comment by zp-xu** [comment]
默认显示在顶部
