### ISSUE TITLE
从日程列表画面进入日程详细画面时间显示不正确

### ISSUE THREAD

**Issue by leonxi** [XJ-GTD/GTD2#55]
再现步骤
1、打开日程列表，点击4月4日创建的日程
2、打开日程画面

画面中的时间没有正确显示，应该是10点，显示18点47...

![image](https://user-images.githubusercontent.com/9960754/55473359-1cf21180-5641-11e9-86c7-0c7eafe97d74.png)

![image](https://user-images.githubusercontent.com/9960754/55473342-106db900-5641-11e9-9ff4-020b49dcf347.png)

**Comment by leonxi** [comment]
补充
提醒也没有正确显示

**Comment by leonxi** [comment]
补充
备注字段宽度不够，另外，内容多的时候没有换行

![image](https://user-images.githubusercontent.com/9960754/55473871-4e1f1180-5642-11e9-87ab-e64afc5155a6.png)

**Comment by zp-xu** [comment]
时间与备注问题已修正
