### ISSUE TITLE
新建日程

### ISSUE THREAD

**Issue by 13564242673** [XJ-GTD/GTD2#56]
1、选择计划文字长的情况下不能完全展示
2、日期和时间选择：不止是日期和时间可以点击选择，箭头也应该可点击选择
3、选择参与人时点击返回应该是到我刚创建这条日程页面，而不是返回到首页
4、选择参与人进去应该直接显示群组和联系人，而不是输入回退后全部展示出来
5、选择参与人选择后应该给个提示框确定发送给谁谁谁，然后提示已发送

**Comment by jy-zhang** [comment]
1，已修正
2，修正箭头去除
3，已修正
4，待定改修

**Comment by jy-zhang** [comment]
5，待修正
