### ISSUE TITLE
语音查询日程，显示创建日程画面

### ISSUE THREAD

**Issue by leonxi** [XJ-GTD/GTD2#59]
再现步骤
1、通过键盘输入语音“我明天有什么事情”
2、页面显示如下图创建日程界面

![image](https://user-images.githubusercontent.com/9960754/55474755-9d664180-5644-11e9-8c7b-69ee2ec8bc15.png)

**Comment by leonxi** [comment]
补充

收到的服务器消息内容如下：
{"header":{"version":"V1.0","sender":"xunfei","datetime":"2019/31/3 19:15:57","describe":["F","S"]},"original":"我明天有什么事情","content":{"F":{"option":"F.C","parameters":{"scd":{"ds":"2019/04/04","de":"2019/04/04"},"fs":[]}},"S":{"option":"S.P","parameters":{"t":"CC"}}},"context":{"client":{"time":1554289968,"option":""}}}

**Comment by jy-zhang** [comment]
已经修复

**Comment by jy-zhang** [comment]
已经修复
