### ISSUE TITLE
日历bug

### ISSUE THREAD

**Issue by 17638848830** [XJ-GTD/GTD2#6]
1、语音输入查询指定日期日程后回复null  然后再说话就没任何回复了。
2、日历界面返回当前日期功能，如果点击本月的一天，再返回当日就没有反应。
3、游客模式，创建日程时，选择参与人界面无参与人但是却有一个空白的选项。
4、语音输入按钮点击后无任何反应，（手机型号：VIVO Y66i A  安卓系统版本7.1）

**Comment by 17638848830** [comment]
补充5、创建日程时，点击备注时，弹出的键盘会把页面的输入框遮盖住。
![3](https://user-images.githubusercontent.com/42716110/51458098-f2f1b880-1d8e-11e9-9521-312a5f49e898.jpg)
![5](https://user-images.githubusercontent.com/42716110/51458106-f8e79980-1d8e-11e9-88ea-b1e557f89456.jpg)
![5 2](https://user-images.githubusercontent.com/42716110/51458115-fdac4d80-1d8e-11e9-9431-a89e16efd87b.jpg)

**Comment by wuyu616818** [comment]
1.4已解决
