### ISSUE TITLE
新创建重复日程，日历页面没有在相关日期显示状态

### ISSUE THREAD

**Issue by leonxi** [XJ-GTD/GTD2#60]
再现步骤
1、创建重复日程
2、返回日程列表
3、返回日历

未显示4月4日以外重复日期中有日程的状态，参考一下图片

![image](https://user-images.githubusercontent.com/9960754/55475036-69d7e700-5645-11e9-953a-c21e89f0e7b8.png)
![image](https://user-images.githubusercontent.com/9960754/55475061-78be9980-5645-11e9-8f44-42559ed51cd7.png)

**Comment by jy-zhang** [comment]
已修复
