### ISSUE TITLE
共享日程，客户端挂掉

### ISSUE THREAD

**Issue by forget1228** [XJ-GTD/GTD2#70]
![微信图片_20190403212106](https://user-images.githubusercontent.com/42605743/55482183-8af50380-5656-11e9-88dd-caa17dd9c2d4.png)

**Comment by forget1228** [comment]
![微信图片_20190403212106](https://user-images.githubusercontent.com/42605743/55482254-b4ae2a80-5656-11e9-9ddb-756b55f6407d.png)

**Comment by jy-zhang** [comment]
收到日程报错，改修ok
