### ISSUE TITLE
存在联系人的日程详细页面中没有显示联系人

### ISSUE THREAD

**Issue by leonxi** [XJ-GTD/GTD2#71]
1、没有地方显示之前选择的共享联系人
2、重新选择联系人之后，删除的联系人被没有通知删除之前共享的日程

**Comment by leonxi** [comment]
重新选择人员不删除已有人选

**Comment by zp-xu** [comment]
1、=》发布人的详情页可以看到了
2，=》不可以删除已共享的参与人
