### ISSUE TITLE
语音创建日程 未显示正确内容

### ISSUE THREAD

**Issue by leonxi** [XJ-GTD/GTD2#73]
收到如下消息
{"header":{"version":"V1.0","sender":"xunfei","datetime":"2019/31/3 22:18:11","describe":["F","SS","S"]},"original":"下周一和张金洋一起去天津出差","content":{"F":{"option":"F.F","parameters":{"fs":[{"n":"zhangjinyang"}]}},"SS":{"option":"SS.C","parameters":{"ti":"天津出差","d":"2019/04/08"}},"S":{"option":"S.P","parameters":{"t":"EE"}}},"context":{"client":{"time":1554300947,"cxt":{"fs":[],"scd":[{"si":"","sn":"天津卫","ui":"","sd":"2019/04/04","st":"","ed":"","et":"","rt":"","ji":"","sr":"","bz":"","tx":"","wtt":0,"pni":"","du":"","gs":""}],"sucess":true},"option":""}}}

显示如下内容
![image](https://user-images.githubusercontent.com/9960754/55485990-1a51e500-565e-11e9-8574-c02736f4b603.png)

**Comment by jy-zhang** [comment]
此问题处理了，但是完全处理好新建还有待测试

**Comment by jy-zhang** [comment]
在测试

**Comment by jy-zhang** [comment]
在测试
