### ISSUE TITLE
首页和侧边栏切换中间不应该有黑色边框线

### ISSUE THREAD

**Issue by 13564242673** [XJ-GTD/GTD2#74]
<img width="409" alt="WX20190404-153326@2x" src="https://user-images.githubusercontent.com/46878072/55537604-2afe6b80-56ef-11e9-94d4-76a0a1380fe7.png">

**Comment by jy-zhang** [comment]
去掉首页的红色把边框线条，加上有点画蛇添足，去掉后此问题修复
