### ISSUE TITLE
系统内建计划 下载后返回日历页面，无显示

### ISSUE THREAD

**Issue by leonxi** [XJ-GTD/GTD2#80]
再现步骤
1、进入菜单、点击计划
2、选择下载农历节气系统计划
3、下载成功后，返回菜单
4、菜单返回日历画面

日历画面没有显示当前月份所属的系统计划日程
右划到日程一览画面，也没有显示

关闭App之后，重新打开，打开日程一览画面，仍然没有显示

**Comment by jy-zhang** [comment]
已修正
