### ISSUE TITLE
备份与恢复 备份后恢复日历显示不正确

### ISSUE THREAD

**Issue by leonxi** [XJ-GTD/GTD2#85]
再现步骤
1、添加日程
2、备份
3、删除冥王星
4、重新安装冥王星
5、登录过程省略...
6、恢复
7、回到日历页面，显示错误
8、到一览页面显示没有日程

日历中任然显示有日程，恢复前的日程
一览画面已经没有了

**Comment by zp-xu** [comment]
已修正
