### ISSUE TITLE
R2 备份时间超过3分钟，每次备份都是备份失败

### ISSUE THREAD

**Issue by leonxi** [XJ-GTD/GTD2#88]
备份联系人的时候，由于本地联系人较多
且联系人表存储了用户头像（张金洋确认该表不应该存储用户头像base64）

导致@native/http组件超时取消请求，nginx报499错误
备份失败

修改成@angular/http后，未报错
（张金洋确认，使用@native/http是为了在后台运行处理时可以使用http请求）
建议判断在前台运行时使用@angular/http访问服务器

**Comment by zp-xu** [comment]
群组的头像不用保存，使用默认头像。参与人头像也不需要保存，关联参与人头像表取。
