### ISSUE TITLE
未解决问题

### ISSUE THREAD

**Issue by leonxi** [XJ-GTD/GTD2#94]
1、联系人重复 席理加
后面找到问题点后解决
2、所有有头像的画面，点击头像需要可以跳转联系人详情画面 张金洋
3、选择联系人画面中显示未注册状态，联系人选择画面排序规则 张金洋
4、默认头像像素太大，需要变小 罗建飞，席理加
5、曹萍收到发送人是空字符串，日程主题为null的日程消息 许兆平
需要查明原因（有可能是服务器在重起，导致没有拿到日程信息）
6、日程详情页面，参与人头像显示调整 张金洋

**Comment by zp-xu** [comment]
4.=》删除时调用服务器接口时，参数没有设值，丁哥调整服务器的save操作

**Comment by leonxi** [comment]
4、默认头像变小已更新

**Comment by leonxi** [comment]
1、联系人重复 席理加
问题已经找到, 系统初始化和登录之后会两次调用setSettings方法,导致两次启动了异步获取联系人注册信息

**Comment by leonxi** [comment]
1、联系人重复 席理加
已经增加了重复调用不处理的逻辑，联系人已经不重复了
